{
  "openapi": "3.0.1",
  "info": {
    "title": "Swagger Demo API",
    "description": "Swagger Demo API Description",
    "termsOfService": "http://www.example.com",
    "contact": {
      "name": "Thanh Le",
      "url": "http://www.example.com",
      "email": "user@example.com"
    },
    "license": {
      "name": "My License",
      "url": "http://www.example.com"
    },
    "version": "v1"
  },
  "paths": {
    "/api/FoodItems": {
      "get": {
        "tags": [
          "FoodItems"
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "text/plain": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/FoodItem"
                  }
                }
              },
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/FoodItem"
                  }
                }
              },
              "text/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/FoodItem"
                  }
                }
              }
            }
          }
        }
      },
      "post": {
        "tags": [
          "FoodItems"
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/FoodItem"
              }
            },
            "text/json": {
              "schema": {
                "$ref": "#/components/schemas/FoodItem"
              }
            },
            "application/*+json": {
              "schema": {
                "$ref": "#/components/schemas/FoodItem"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "text/plain": {
                "schema": {
                  "$ref": "#/components/schemas/FoodItem"
                }
              },
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/FoodItem"
                }
              },
              "text/json": {
                "schema": {
                  "$ref": "#/components/schemas/FoodItem"
                }
              }
            }
          }
        }
      }
    },
    "/api/FoodItems/{id}": {
      "get": {
        "tags": [
          "FoodItems"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int32"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "text/plain": {
                "schema": {
                  "$ref": "#/components/schemas/FoodItem"
                }
              },
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/FoodItem"
                }
              },
              "text/json": {
                "schema": {
                  "$ref": "#/components/schemas/FoodItem"
                }
              }
            }
          }
        }
      },
      "put": {
        "tags": [
          "FoodItems"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int32"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/FoodItem"
              }
            },
            "text/json": {
              "schema": {
                "$ref": "#/components/schemas/FoodItem"
              }
            },
            "application/*+json": {
              "schema": {
                "$ref": "#/components/schemas/FoodItem"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      },
      "delete": {
        "tags": [
          "FoodItems"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int32"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "text/plain": {
                "schema": {
                  "$ref": "#/components/schemas/FoodItem"
                }
              },
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/FoodItem"
                }
              },
              "text/json": {
                "schema": {
                  "$ref": "#/components/schemas/FoodItem"
                }
              }
            }
          }
        }
      }
    },
    "/WeatherForecast": {
      "get": {
        "tags": [
          "WeatherForecast"
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "text/plain": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/WeatherForecast"
                  }
                }
              },
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/WeatherForecast"
                  }
                }
              },
              "text/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/WeatherForecast"
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "FoodItem": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "format": "int32"
          },
          "imgSource": {
            "type": "string",
            "nullable": true
          },
          "title": {
            "type": "string",
            "nullable": true
          },
          "desc": {
            "type": "string",
            "nullable": true
          }
        },
        "additionalProperties": false
      },
      "WeatherForecast": {
        "type": "object",
        "properties": {
          "date": {
            "type": "string",
            "format": "date-time"
          },
          "temperatureC": {
            "type": "integer",
            "format": "int32"
          },
          "temperatureF": {
            "type": "integer",
            "format": "int32",
            "readOnly": true
          },
          "summary": {
            "type": "string",
            "nullable": true
          }
        },
        "additionalProperties": false
      }
    }
  }
}